### ISSUE TITLE
AziAudio_Legacy has bad savestate loading delay, not present in old AziAudio and Jabo DirectSound

### ISSUE THREAD

**Issue by BruceShankleIV** [pj64team/AziAudio_Legacy#6] opened 2024-06-10 20:59 UTC
Title is self-explanatory (just press F5/F7 or use save/restore under systems). i don't really need to say much more, this is not something that is like, also dependent on video/rsp/input plugin or anything. Old AziAudio = Original AziAudio 0.70 WIP 10. Also, 10c should be depreciated with 10b, it is not saving the settings correctly. specifically, I try to change the sound driver and it does not save the change after i exit the menu. so, if you guys decide to fix this issue please work off the b version because that one is better.

i was told to "assign it to azi and icepsir8" so i will try to assign this to them after i post this message. EDIT: i cant figure out how github works so someone else will assign to them.

EDIT 2: Godamnit apparently the issue is supposed to be posted in this git repo not the other one. deleting the old post after i post this one,.

**Comment by Azimer** [comment] 2024-06-17 16:00
This worked fine on the Legacy release.  Is that what you are using or a different version (PJ64+)?  What is meant by delay?  Seconds, minutes, just longer?  Both save and restore?

As far as saving settings, can I get a clear step by step on what you are doing with a clean configuration so I can reproduce it.  The save settings is a bit awkward but for Legacy I was fine because I wanted to move forward with MiB.

**Comment by BruceShankleIV** [comment] 2024-06-18 00:01
I did a recording with a clean version of pj64 legacy for an example, I didn't use any special configuration or nothing. This will also happen with any game, not just SM64. It didn't work fine on legacy, but probably flew under the radar during development because this isn't as noticeable for some as it is for others, as the amount of delay that happens when loading (not saving) a savestate seems to vary across different hardware. https://youtu.be/O8AJo3RYkyU The delay isn't too bad in the video, but it's been a lot worse before.

**Comment by Azimer** [comment] 2024-06-19 19:41
This issue is not specific to AziAudio_Legacy.  https://youtu.be/FFJjZya38xk

Sorry this is a different issue but I will leave it here anyway.  This is the stutter on load issue.

**Comment by Azimer** [comment] 2024-06-19 19:52
I see and recognize the issue.  If I had to venture a guess, it has to do with the overhead of reinitializing the audio plugin every time the state loads.  This is specific to the DirectSound 8 drivers.

**Comment by Azimer** [comment] 2024-06-19 22:52
This should be resolved in https://github.com/pj64team/AziAudio_Legacy/pull/7 .

**Closed as completed by Azimer** 2024-06-19 22:52 UTC
